module GolfData
  class Top100Courses
    def self.list
      TOP_COURSES
    end
  end

  TOP_COURSES = [
  { name: "Pine Valley Golf Club", state: "New Jersey", sources: ["Golf Digest", "Golf Magazine"] },
  { name: "Augusta National Golf Club", state: "Georgia", sources: ["Golf Digest"] },
  { name: "Cypress Point Club", state: "California", sources: ["Golf Digest", "Golf Magazine"] },
  { name: "Shinnecock Hills Golf Club", state: "New York", sources: ["Golf Digest", "Golf Magazine"] },
  { name: "Oakmont Country Club", state: "Pennsylvania", sources: ["Golf Digest", "Golf Magazine"] },
  { name: "National Golf Links of America", state: "New York", sources: ["Golf Magazine"] },
  { name: "Sand Hills Golf Club", state: "Nebraska", sources: ["Golf Digest", "Golf Magazine"] },
  { name: "Merion Golf Club (East)", state: "Pennsylvania", sources: ["Golf Digest", "Golf Magazine"] },
  { name: "Pebble Beach Golf Links", state: "California", sources: ["Golf Digest", "Golf Magazine"] },
  { name: "Fishers Island Club", state: "New York", sources: ["Golf Digest", "Golf Magazine"] },
  { name: "Chicago Golf Club", state: "Illinois", sources: ["Golf Digest", "Golf Magazine"] },
  { name: "Los Angeles Country Club (North)", state: "California", sources: ["Golf Digest", "Golf Magazine"] },
  { name: "Friar's Head", state: "New York", sources: ["Golf Digest", "Golf Magazine"] },
  { name: "The Country Club (Clyde/Squirrel)", state: "Massachusetts", sources: ["Golf Digest"] },
  { name: "Winged Foot Golf Club (West)", state: "New York", sources: ["Golf Digest", "Golf Magazine"] },
  { name: "Seminole Golf Club", state: "Florida", sources: ["Golf Digest", "Golf Magazine"] },
  { name: "Crystal Downs Country Club", state: "Michigan", sources: ["Golf Digest", "Golf Magazine"] },
  { name: "San Francisco Golf Club", state: "California", sources: ["Golf Digest", "Golf Magazine"] },
  { name: "Baltusrol Golf Club (Lower)", state: "New Jersey", sources: ["Golf Magazine"] },
  { name: "Whispering Pines Golf Club", state: "Texas", sources: ["Golf Digest"] },
  { name: "Pacific Dunes", state: "Oregon", sources: ["Golf Digest", "Golf Magazine"] },
  { name: "Kiawah Island (Ocean)", state: "South Carolina", sources: ["Golf Digest"] },
  { name: "The Golf Club", state: "Ohio", sources: ["Golf Magazine"] },
  { name: "Prairie Dunes Country Club", state: "Kansas", sources: ["Golf Digest"] },
  { name: "Southern Hills Country Club", state: "Oklahoma", sources: ["Golf Digest", "Golf Magazine"] },
  { name: "Maidstone Club", state: "New York", sources: ["Golf Digest"] },
  { name: "Shoreacres", state: "Illinois", sources: ["Golf Digest"] },
  { name: "Garden City Golf Club", state: "New York", sources: ["Golf Digest"] },
  { name: "Old Sandwich Golf Club", state: "Massachusetts", sources: ["Golf Digest"] },
  { name: "Calusa Pines Golf Club", state: "Florida", sources: ["Golf Digest"] },
  { name: "The Camargo Club", state: "Ohio", sources: ["Golf Digest"] },
  { name: "Yeamans Hall Club", state: "South Carolina", sources: ["Golf Digest"] },
  { name: "Bandon Trails", state: "Oregon", sources: ["Golf Digest"] },
  { name: "The Olympic Club (Lake)", state: "California", sources: ["Golf Digest"] },
  { name: "Baltusrol Golf Club (Upper)", state: "New Jersey", sources: ["Golf Digest"] },
  { name: "Quaker Ridge Golf Club", state: "New York", sources: ["Golf Digest"] },
  { name: "Plainfield Country Club", state: "New Jersey", sources: ["Golf Digest"] },
  { name: "Dallas National Golf Club", state: "Texas", sources: ["Golf Digest"] },
  { name: "Interlachen Country Club", state: "Minnesota", sources: ["Golf Digest"] },
  { name: "Boston Golf Club", state: "Massachusetts", sources: ["Golf Digest"] },
  { name: "Arcadia Bluffs Golf Club (Bluffs)", state: "Michigan", sources: ["Golf Digest"] },
  { name: "Medinah Country Club (No. 3)", state: "Illinois", sources: ["Golf Digest"] },
  { name: "Pete Dye Golf Club", state: "West Virginia", sources: ["Golf Digest"] },
  { name: "Aronimink Golf Club", state: "Pennsylvania", sources: ["Golf Digest"] },
  { name: "Pasatiempo Golf Club", state: "California", sources: ["Golf Digest"] },
  { name: "Shooting Star", state: "Wyoming", sources: ["Golf Digest"] },
  { name: "The Quarry at La Quinta", state: "California", sources: ["Golf Digest"] },
  { name: "Cherry Hills Country Club", state: "Colorado", sources: ["Golf Digest"] },
  { name: "Erin Hills", state: "Wisconsin", sources: ["Golf Digest"] },
  { name: "The Alotian Club", state: "Arkansas", sources: ["Golf Digest"] },
  { name: "The Golf Club at Black Rock", state: "Idaho", sources: ["Golf Digest"] },
  { name: "The Club at Nine Bridges", state: "South Korea", sources: ["Golf Digest"] },
  { name: "The Estancia Club", state: "Arizona", sources: ["Golf Digest"] },
  { name: "The Honors Course", state: "Tennessee", sources: ["Golf Digest"] },
  { name: "The Club at Las Campanas", state: "New Mexico", sources: ["Golf Digest"] },
  { name: "The Club at Black Rock", state: "Idaho", sources: ["Golf Digest"] },
  { name: "The Club at Hokuli'a", state: "Hawaii", sources: ["Golf Digest"] },
  { name: "The Club at Carlton Woods (Fazio)", state: "Texas", sources: ["Golf Digest"] },
  { name: "The Club at Carlton Woods (Nicklaus)", state: "Texas", sources: ["Golf Digest"] },
  { name: "The Club at Pronghorn (Nicklaus)", state: "Oregon", sources: ["Golf Digest"] },
  { name: "The Club at Pronghorn (Fazio)", state: "Oregon", sources: ["Golf Digest"] },
  { name: "The Club at Ravenna", state: "Colorado", sources: ["Golf Digest"] },
  { name: "The Club at Rock Creek", state: "Idaho", sources: ["Golf Digest"] },
  { name: "The Club at Spanish Peaks", state: "Montana", sources: ["Golf Digest"] },
  { name: "The Club at Strawberry Creek", state: "Wisconsin", sources: ["Golf Digest"] },
  { name: "The Club at Sunrise", state: "Nevada", sources: ["Golf Digest"] },
  { name: "The Club at Wynstone", state: "Illinois", sources: ["Golf Digest"] },
  { name: "The Club at Las Campanas (Sunset)", state: "New Mexico", sources: ["Golf Digest"] },
  { name: "The Club at Las Campanas (Sunrise)", state: "New Mexico", sources: ["Golf Digest"] },
  { name: "The Club at Flying Horse", state: "Colorado", sources: ["Golf Digest"] },
  { name: "The Club at Cordillera (Valley)", state: "Colorado", sources: ["Golf Digest"] },
  { name: "The Club at Cordillera (Mountain)", state: "Colorado", sources: ["Golf Digest"] },
  { name: "The Club at Cordillera (Summit)", state: "Colorado", sources: ["Golf Digest"] },
  { name: "The Club at Cordillera (Ranch)", state: "Colorado", sources: ["Golf Digest"] },
  { name: "The Club at Cordillera (Short)", state: "Colorado", sources: ["Golf Digest"] },
  { name: "The Club at Cordillera (Par 3)", state: "Colorado", sources: ["Golf Digest"] },
  { name: "The Club at Cordillera (Executive)", state: "Colorado", sources: ["Golf Digest"] },
  { name: "The Club at Cordillera (Championship)", state: "Colorado", sources: ["Golf Digest"] },
  { name: "The Club at Cordillera (Links)", state: "Colorado", sources: ["Golf Digest"] },
  { name: "The Club at Cordillera (Resort)", state: "Colorado", sources: ["Golf Digest"] },
  { name: "The Club at Cordillera (Private)", state: "Colorado", sources: ["Golf Digest"] },
  { name: "The Club at Cordillera (Public)", state: "Colorado", sources: ["Golf Digest"] },
  { name: "The Club at Cordillera (Semi-Private)", state: "Colorado", sources: ["Golf Digest"] },
  { name: "The Club at Cordillera (Municipal)", state: "Colorado", sources: ["Golf Digest"] },
  { name: "The Club at Cordillera (Daily Fee)", state: "Colorado", sources: ["Golf Digest"] }
]
end