module GolfData
  class Top100Courses
    def self.list
      TOP_COURSES
    end
  end

  TOP_COURSES = [
    { name: "Pine Valley Golf Club", state: "New Jersey" },
    { name: "Augusta National Golf Club", state: "Georgia" },
    { name: "Cypress Point Club", state: "California" },
    { name: "Shinnecock Hills Golf Club", state: "New York" },
    { name: "Oakmont Country Club", state: "Pennsylvania" },
    { name: "Merion Golf Club (East)", state: "Pennsylvania" },
    { name: "National Golf Links of America", state: "New York" },
    { name: "Sand Hills Golf Club", state: "Nebraska" },
    { name: "Fishers Island Club", state: "New York" },
    { name: "Pebble Beach Golf Links", state: "California" },
    { name: "Los Angeles Country Club (North)", state: "California" },
    { name: "Chicago Golf Club", state: "Illinois" },
    { name: "Winged Foot Golf Club (West)", state: "New York" },
    { name: "Seminole Golf Club", state: "Florida" },
    { name: "Crystal Downs Country Club", state: "Michigan" },
    { name: "San Francisco Golf Club", state: "California" },
    { name: "The Country Club (Clyde/Squirrel)", state: "Massachusetts" },
    { name: "Friar's Head", state: "New York" },
    { name: "Pacific Dunes", state: "Oregon" },
    { name: "Whistling Straits (Straits)", state: "Wisconsin" },
    { name: "Kiawah Island (Ocean)", state: "South Carolina" },
    { name: "The Golf Club", state: "Ohio" },
    { name: "Prairie Dunes Country Club", state: "Kansas" },
    { name: "Southern Hills Country Club", state: "Oklahoma" },
    { name: "Maidstone Club", state: "New York" },
    { name: "Shoreacres", state: "Illinois" },
    { name: "Garden City Golf Club", state: "New York" },
    { name: "Old Sandwich Golf Club", state: "Massachusetts" },
    { name: "Calusa Pines Golf Club", state: "Florida" },
    { name: "The Camargo Club", state: "Ohio" },
    { name: "Yeamans Hall Club", state: "South Carolina" },
    { name: "Bandon Trails", state: "Oregon" },
    { name: "The Olympic Club (Lake)", state: "California" },
    { name: "Baltusrol Golf Club (Lower)", state: "New Jersey" },
    { name: "Quaker Ridge Golf Club", state: "New York" },
    { name: "Plainfield Country Club", state: "New Jersey" },
    { name: "Dallas National Golf Club", state: "Texas" },
    { name: "Interlachen Country Club", state: "Minnesota" },
    { name: "Boston Golf Club", state: "Massachusetts" },
    { name: "Arcadia Bluffs Golf Club (Bluffs)", state: "Michigan" },
    { name: "Medinah Country Club (No. 3)", state: "Illinois" },
    { name: "Pete Dye Golf Club", state: "West Virginia" },
    { name: "Aronimink Golf Club", state: "Pennsylvania" },
    { name: "Pasatiempo Golf Club", state: "California" },
    { name: "Shooting Star", state: "Wyoming" },
    { name: "The Quarry at La Quinta", state: "California" },
    { name: "Cherry Hills Country Club", state: "Colorado" },
    { name: "Erin Hills", state: "Wisconsin" },
    { name: "The Alotian Club", state: "Arkansas" },
    { name: "The Golf Club at Black Rock", state: "Idaho" },
    { name: "Somerset Hills Country Club", state: "New Jersey" },
    { name: "Myopia Hunt Club", state: "Massachusetts" },
    { name: "Monterey Peninsula Country Club (Shore)", state: "California" },
    { name: "Sleepy Hollow Country Club", state: "New York" },
    { name: "The Valley Club of Montecito", state: "California" },
    { name: "Baltusrol Golf Club (Upper)", state: "New Jersey" },
    { name: "The Estancia Club", state: "Arizona" },
    { name: "The Honors Course", state: "Tennessee" },
    { name: "Riviera Country Club", state: "California" },
    { name: "Bethpage Black", state: "New York" },
    { name: "TPC Sawgrass (Stadium)", state: "Florida" },
    { name: "Torrey Pines (South)", state: "California" },
    { name: "Hazeltine National Golf Club", state: "Minnesota" },
    { name: "Congressional Country Club (Blue)", state: "Maryland" },
    { name: "Muirfield Village Golf Club", state: "Ohio" },
    { name: "East Lake Golf Club", state: "Georgia" },
    { name: "Harbour Town Golf Links", state: "South Carolina" },
    { name: "Spyglass Hill Golf Course", state: "California" },
    { name: "Bandon Dunes", state: "Oregon" },
    { name: "Old Macdonald", state: "Oregon" },
    { name: "Sheep Ranch", state: "Oregon" },
    { name: "Streamsong (Red)", state: "Florida" },
    { name: "Streamsong (Blue)", state: "Florida" },
    { name: "Cabot Links", state: "Nova Scotia" },
    { name: "Cabot Cliffs", state: "Nova Scotia" },
    { name: "Tobacco Road Golf Club", state: "North Carolina" },
    { name: "Mid Pines Inn & Golf Club", state: "North Carolina" },
    { name: "Pine Needles Lodge & Golf Club", state: "North Carolina" },
    { name: "Pinehurst No. 2", state: "North Carolina" },
    { name: "Pinehurst No. 4", state: "North Carolina" },
    { name: "Wade Hampton Golf Club", state: "South Carolina" },
    { name: "The Ocean House", state: "Rhode Island" },
    { name: "Nantucket Golf Club", state: "Massachusetts" },
    { name: "Sankaty Head Golf Club", state: "Massachusetts" },
    { name: "The Preserve Golf Club", state: "California" },
    { name: "Chambers Bay", state: "Washington" },
    { name: "Gamble Sands", state: "Washington" },
    { name: "Wine Valley Golf Club", state: "California" },
    { name: "Rustic Canyon Golf Course", state: "California" },
    { name: "Coore & Crenshaw Course at Trinity Forest", state: "Texas" },
    { name: "Old American Golf Club", state: "Texas" },
    { name: "Dormie Club", state: "North Carolina" },
    { name: "Forest Dunes Golf Club", state: "Michigan" },
    { name: "The Loop (Red)", state: "Michigan" },
    { name: "The Loop (Black)", state: "Michigan" },
    { name: "Mammoth Dunes", state: "Wisconsin" },
    { name: "Sand Valley Golf Resort", state: "Wisconsin" },
    { name: "Sedge Valley", state: "Wisconsin" },
    { name: "The Lido", state: "Wisconsin" },
    { name: "Sweetens Cove Golf Club", state: "Tennessee" },
    { name: "Ballyhack Golf Club", state: "Virginia" },
    { name: "Royal New Kent", state: "Virginia" },
    { name: "Kinloch Golf Club", state: "Virginia" },
    { name: "Farmlinks Golf Club", state: "Alabama" },
    { name: "The Clubs of Kingsley", state: "Michigan" }
  ]
end